/**
 * Export utilities for RECORE
 * Allows users to export their trajectory and roadmap data
 */

/**
 * Export trajectory data as JSON
 */
export function exportTrajectoryJSON(trajectory, insights, user) {
  const data = {
    exportDate: new Date().toISOString(),
    user: {
      name: user.name,
      email: user.email,
      grade: user.grade,
      board: user.board
    },
    trajectory: {
      directionVector: trajectory.directionVector,
      stabilityScore: trajectory.stabilityScore,
      explorationMode: trajectory.explorationMode,
      confidenceMomentum: trajectory.confidenceMomentum,
      version: trajectory.version
    },
    insights: insights
  };

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `recore-trajectory-${Date.now()}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export roadmap as markdown
 */
export function exportRoadmapMarkdown(roadmap, user, trajectory) {
  let markdown = `# RECORE Learning Roadmap\n\n`;
  markdown += `**Student:** ${user.name}\n`;
  markdown += `**Grade:** ${user.grade} | **Board:** ${user.board}\n`;
  markdown += `**Generated:** ${new Date().toLocaleDateString()}\n\n`;

  if (trajectory) {
    markdown += `## Learning Profile\n\n`;
    markdown += `- **Stability Score:** ${Math.round(trajectory.stabilityScore * 100)}%\n`;
    markdown += `- **Mode:** ${trajectory.explorationMode ? 'Exploration' : 'Consolidation'}\n`;
    markdown += `- **Confidence Momentum:** ${Math.round(trajectory.confidenceMomentum * 100)}%\n\n`;
    
    markdown += `### Trajectory Coordinates\n`;
    markdown += `- **Abstraction:** ${trajectory.directionVector.abstraction.toFixed(2)}\n`;
    markdown += `- **Structure:** ${trajectory.directionVector.structure.toFixed(2)}\n`;
    markdown += `- **Risk:** ${trajectory.directionVector.risk.toFixed(2)}\n\n`;
  }

  markdown += `---\n\n## Roadmap Modules\n\n`;

  if (roadmap && roadmap.length > 0) {
    roadmap.forEach((module, idx) => {
      markdown += `### ${idx + 1}. ${module.name}\n\n`;
      markdown += `**Subject:** ${module.subject}\n`;
      markdown += `**Estimated Time:** ${module.estimatedWeeks} weeks\n`;
      markdown += `**Difficulty:** ${module.difficulty}\n\n`;
      markdown += `**Intent:** ${module.intent}\n\n`;

      markdown += `#### Checkpoints\n\n`;
      module.checkpoints.forEach((checkpoint, cpIdx) => {
        markdown += `##### Checkpoint ${checkpoint.number}: ${checkpoint.title}\n\n`;
        
        if (checkpoint.type === 'content' && checkpoint.topics) {
          markdown += `**Topics:**\n`;
          checkpoint.topics.forEach(topic => {
            markdown += `- ${topic}\n`;
          });
          markdown += `\n`;
        }

        if (checkpoint.type === 'exploration' && checkpoint.task) {
          markdown += `**Exploration Task:**\n`;
          markdown += `${checkpoint.task.description}\n\n`;
          markdown += `*Rationale:* ${checkpoint.task.rationale}\n\n`;
        }

        if (checkpoint.type === 'progress_check') {
          markdown += `**Progress Checkpoint:** Self-assessment to evaluate understanding\n\n`;
        }
      });

      if (module.reflectionTask) {
        markdown += `#### Reflection Task\n\n`;
        markdown += `${module.reflectionTask.prompt}\n\n`;
      }

      markdown += `---\n\n`;
    });
  } else {
    markdown += `*No roadmap generated yet. Complete the questionnaire and commit to curriculum.*\n\n`;
  }

  markdown += `## Important Notes\n\n`;
  markdown += `- This roadmap is a **projection**, not a prescription\n`;
  markdown += `- It adapts based on your learning trajectory\n`;
  markdown += `- All recommendations are reversible\n`;
  markdown += `- Insights are generated from behavioral signals, not academic performance\n\n`;

  markdown += `---\n\n`;
  markdown += `*Generated by RECORE - Trajectory Inference Engine*\n`;

  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `recore-roadmap-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export university preferences as CSV
 */
export function exportPreferencesCSV(preferenceList) {
  let csv = 'Rank,University,Branch,Location,Type,Score,Admission Chance,Explanation\n';

  preferenceList.forEach(pref => {
    const row = [
      pref.rank,
      `"${pref.universityName}"`,
      `"${pref.branch}"`,
      `"${pref.location}"`,
      pref.instituteType,
      pref.totalScore,
      pref.estimatedAdmissionChance,
      `"${pref.explanation}"`
    ].join(',');
    csv += row + '\n';
  });

  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `recore-university-preferences-${Date.now()}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
